### ISSUE TITLE
JsonNodeValueResolver for Handlebars

### ISSUE THREAD

**Issue by schattenhaar** [pmlopes/yoke#142]
How can I add a JsonNodeValueResolver or other resolvers to Handlebars in Yoke? Resolving {{a.b.c}} in Handlebars templates in Yoke does not work. In Handlebars Java it is possible. In Yoke I found no way to do this, because the context is not exposed. I want to add the following resolver as described with Handlebars Java for all templates:

Context context = Context
  .newBuilder(model)
  .resolver(JsonNodeValueResolver.INSTANCE)
  .build();

and then call request.response().render("name") using this context.

**Comment by pmlopes** [comment]
If this is still required please create an issue at [vertx-web](https://github.com/vert-x3/vertx-web)
