### ISSUE TITLE
Broken link in docs?

### ISSUE THREAD

**Issue by aliakhtar** [pmlopes/yoke#145]
The link: http://pmlopes.github.io/yoke/Session.html

appears to be broken. Is there a fixed version somewhere?

**Comment by pmlopes** [comment]
I am about to update the project site to be in sync with the current code, with a release 2.0.13 next week

**Comment by aliakhtar** [comment]
There's something like yoke that's built into vertx 3.0 called apex, so there might not be any more need for yoke beyond vertx 3

**Comment by pmlopes** [comment]
in a way true, apex as a rewrite of yoke, and reuse of its code to fit the vert.x 3 API but until 3 is out and all extra modules are converted you might need yoke though :)

**Comment by pmlopes** [comment]
btw i've uploaded a new site with better docs
