### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by jtroxel** [pmlopes/yoke#146]
I am trying to put Yoke into the vertx maven archetype project.  I added the yoke dependency to the pom,  added a js test file, and pointed the mod.js to that file.  When trying to runMod through maven, I get
   org.mozilla.javascript.JavaScriptException: Error: Module "yoke/Yoke" not found. (file:/Users/jtroxel/dev/codecraft/yoke1/src/main/resources/test_yoke.js#8)
...from the line...
var Yoke = require('yokejs/Yoke');

FWIW, I also followed the bootstrapping instructions with gradle, in a new project, and I get the exact same error.

**Comment by pmlopes** [comment]
I'll have to review bootstrapping a project it has been a while...

**Comment by pmlopes** [comment]
I will try to make a new release next monday that fixes this 2.0.13.

**Comment by pmlopes** [comment]
2.0.13 is being uploaded to central
