### ISSUE TITLE
Yoke Extras including old Yoke version

### ISSUE THREAD

**Issue by wieki** [pmlopes/yoke#147]
When using version 2.0.11 of Yoke and Yoke Extras, Yoke Extras will also pull in Yoke version 1.0.12 (it's linked in the mod.json file) should this be the 2.0.11 version of Yoke instead?

**Comment by pmlopes** [comment]
Yes that's a bug i'll fix it tomorrow.

Thanks!
Paulo.


-----Original Message-----
From: wieki
Sent:  15/02/2015, 12:51 
To: pmlopes/yoke
Subject: [yoke] Yoke Extras including old Yoke version (#147)


When using version 2.0.11 of Yoke and Yoke Extras, Yoke Extras will also pull in Yoke version 1.0.12 (it's linked in the mod.json file) should this be the 2.0.11 version of Yoke instead?

---
Reply to this email directly or view it on GitHub:
https://github.com/pmlopes/yoke/issues/147

**Comment by pmlopes** [comment]
2.0.12 is being uploaded to central

**Comment by wieki** [comment]
Great, nice job!
