### ISSUE TITLE
JS templating engine

### ISSUE THREAD

**Issue by stuplum** [pmlopes/yoke#151]
I would like to use a different templating engine. I have been looking at the javascript and groovy examples for inspiration. However, I've run into a couple of problems.

1. In the JS example there is a line `yoke.engine('html', new MicroTemplatingEngine());` This line was throwing an error about expecting an object, but received a string... Poking around in Yoke.js, the engine method only appears to take a single argument...

```
JSYoke.prototype.engine = function (engine) {
 // verify if the engine is already a Engine instance
 if (engine.jEngine !== undefined) {
 // in this case pass it directly to the jYoke
 this.jYoke.engine(engine.jEngine);
 } else {
 this.jYoke.engine(new com.jetdrone.vertx.yoke.Engine(engine));
 }
};
```

This would explain the error, but the JS and groovy example both show passing a string of the file type as the first argument to the engine method. What is supposed to happen with the file type argument?

2. Taking inspiration from the groovy example, I assumed I would be able to 'require' another type of templating engine, so I tried...

```
var TemplateEngine = require('yoke/engine/HandlebarsEngine');
```

But this isn't available, is there a way to use different templating engines using the JS implementation?

**Comment by pmlopes** [comment]
sorry but most of the js port of yoke is far behind, since Vert.x3 is almost out I'd recommend you to use its vert.x-web since its API is always up to date to the core and it is quite close to Yoke.
