### ISSUE TITLE
Provide relative path within middleware (path without mount point)

### ISSUE THREAD

**Issue by fkranawetter** [pmlopes/yoke#156]
Calling `request.path()` always returns the full path of the incoming request. This is basically fine if a middleware has been mounted on the root path using `use(middleware)`. For example:

```java
yoke.use(myDemoRestMiddleware);
```

However, if the middleware is mounted below a specific path prefix, like this ...

```java
yoke.use("/api/v1", myDemoRestMiddleware);
```

... one would expect, that path returns only the relative path segment. Having an incoming request `/api/v1/demo`, a call to `request.path()` within my middleware should return `/demo` instead of  `/api/v1/demo`.

That way the middleware doesn't need to know below which path segments it has been mounted (could be more than one). Side note: Express.js only returns the relative path, i.e. the path without the mount point.

**Comment by pmlopes** [comment]
I'd recomment to switch to vertx-web since no development is happening here. Vertx-Web is the official web stack that evolved from Yoke.
