### ISSUE TITLE
upgrade to vertx3

### ISSUE THREAD

**Issue by pmlopes** [pmlopes/yoke#164]
Goals:
* keep same API
* upgrade to java8

Non goals:
* upgrade to nashorn
* if too complicated we might drop js or groovy

**Comment by ericlw** [comment]
I'm interested in using this library with Vertx3, thoughts on the progress?

**Comment by pmlopes** [comment]
Hi, it has been ported but never published to maven central. I'll publish it but advice to migrate to vertx web where development happens now.

**Comment by ericlw** [comment]
Interesting! In that case I'll look further there, instead of with Yoke, I see you contribute to the Vertx repositories.

Are you familiar with any performance comparisons with the Vertx Web framework (compared with vertx raw, vertx + yoke, node + express, etc)

**Comment by pmlopes** [comment]
I don't have any specific numbers but can confirm that for benchmarks such as TechEmpower which are not representative of real world applications Vert.x core is by far faster than node + express, there is a code submitted but not run yet that shows that vertx-web is also faster.

I've no number of yoke and i'm not planning to do so for now since it requires some time to implement and as I've said I recommend to use vertx-web due to the fact that is where code is evolving and there is a huge user base. Which translates to better field tested code.
