### ISSUE TITLE
Add the Rythm template engine

### ISSUE THREAD

**Issue by orefalo** [pmlopes/yoke#26]
Nice work, was waiting for something similar.
  This "issue" may be marked as an enhancement.

Add the Rythm template engine.  http://www.rythmengine.com/doc/feature
   One of the best in its kind IMHO.

Actually coming from node.js this template engine looks like a must have as well -> https://github.com/jknack/handlebars.java

Sincerely,

**Comment by pmlopes** [comment]
Due to the fact that Vert.x3 has its own Template engine implementation and Yoke was a Vert.x2 solution i will close this issue and if needed please report it against Vert.x3-Web
